apps/events/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.events.views import EventView,CreateEvent,DashboardEvent,EventImages,EventTicket,PublishEvent,EventPlanner,EventSponsor,EventGuest,Delete,EventGallery,EventSchedules,getEvents,GetStatsTickets,TicketsSold,ReqAssistance,toAccept,EventShellers,addShellerInTheGroup,destroyEvent,EventConfigurations,changeOptionEvent,EventMethodsPaymentEventOffline,configPlatformPayment

urlpatterns = [
    url(r'^new$', login_required(CreateEvent), name='new'),
    url(r'^view/(?P<view>\w+)/(?P<idevent>\d+)/$', EventView, name='event_view_home'), #Basada en funciones
    url(r'^dashboard/(?P<idevent>\d+)/$', login_required(DashboardEvent), name='dashboard'), #Basada en funciones
    url(r'^dashboard/images/(?P<idevent>\d+)/$', login_required(EventImages), name='event_images'),  # Basada en funciones
    url(r'^dashboard/gallery/(?P<idevent>\d+)/$', login_required(EventGallery), name='event_gallery'),  # Basada en funciones
    url(r'^dashboard/tickets/(?P<idevent>\d+)/$', login_required(EventTicket), name='event_tickets'),# Basada en funciones
    url(r'^dashboard/publish/(?P<idevent>\d+)/$', login_required(PublishEvent), name='publish'),# Basada en funciones
    url(r'^dashboard/planners/(?P<idevent>\d+)/$', login_required(EventPlanner), name='event_planners'),# Basada en funciones
    url(r'^dashboard/sponsors/(?P<idevent>\d+)/$', login_required(EventSponsor), name='event_sponsors'),# Basada en funciones
    url(r'^dashboard/guests/(?P<idevent>\d+)/$', login_required(EventGuest), name='event_guests'),# Basada en funciones
    url(r'^dashboard/schedules/(?P<idevent>\d+)/$', login_required(EventSchedules), name='event_schedules'),# Basada en funciones
    url(r'^dashboard/shellers/(?P<idevent>\d+)/$', login_required(EventShellers), name='event_shellers'),# Basada en funciones
    url(r'^dashboard/configurations/(?P<idevent>\d+)/$', login_required(EventConfigurations), name='event_configurations'),# Basada en funciones
    url(r'^dashboard/paymentoffline/(?P<idevent>\d+)/$', login_required(EventMethodsPaymentEventOffline), name='paymentoffline'),# Basada en funciones
    url(r'^dashboard/delete/(?P<idevent>\d+)/$', login_required(Delete), name='event_delete'),
    url(r'^search/$', login_required(getEvents), name='getEvents'),
    url(r'^stats/tickets/$', login_required(GetStatsTickets), name='statsTickets'),
    url(r'^sold/tickets/$', login_required(TicketsSold), name='ticketsSold'),
    url(r'^requestassistance/$', login_required(ReqAssistance), name='reqassistance'),
    url(r'^toaccept/$', login_required(toAccept), name='toaccept'),
    url(r'^addsheller/$', login_required(addShellerInTheGroup), name='addsheller'),
    url(r'^destroy/$', login_required(destroyEvent), name='destroy'),
    url(r'^change_option/$', login_required(changeOptionEvent), name='changeOption'),
    url(r'^platformpayment/$', login_required(configPlatformPayment), name='platformpayment'),
]

iticket/urls.py
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm,password_reset_complete

from apps.events.views import Home
from apps.users.views import UserRegister

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include ('apps.events.urls', namespace="events")),
    url(r'^tickets/', include ('apps.tickets.urls', namespace="tickets")),
    url(r'^profile/', include('apps.users.urls', namespace="profile")),
    url(r'^register/', UserRegister, name="register"),
    url(r'^$', Home, name='home'),
    url(r'^accounts/login/', login, {'template_name': 'index.html'}, name='login'),
    url('', include('social_django.urls', namespace='social')),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, {'template_name': 'registration/password_reset_form.html', 'email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'} , name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, {'template_name':'registration/password_reset_confirm.html'} ,name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete,{'template_name':'registration/password_reset_complete.html'} ,name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/event_planner/forms.py
from django import forms
from apps.event_planner.models import EventPlannerModel,SponsorModel,GuestsModels,ShellersGroupModel,ShellerModel

class EventPlannerModelForm(forms.ModelForm):

    class Meta:
        model = EventPlannerModel
        fields = [
            'name',
            'image',
            'description',
            'twitter',
            'facebook',
        ]

        labels = {
            'name' : 'Nombre',
            'image' : 'Foto Organizador',
            'description' : 'Descripcion',
            'twitter' : 'Twitter',
            'facebook' : 'Facebook',
        }

        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),
            'image' : forms.FileInput(),
            'description' : forms.Textarea(attrs={'class':'form-control'}),
            'twitter' : forms.TextInput(attrs={'class':'form-control'}),
            'facebook' : forms.TextInput(attrs={'class':'form-control'}),
        }

class SponsorModelForm(forms.ModelForm):
    class Meta:
        model = SponsorModel
        fields = [
            'title',
            'logo',
        ]

        labels = {
            'title' : 'Nombre del patrocinador',
            'logo' : 'Logo del patrocinador',
        }

        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'logo' : forms.FileInput(),
        }

class GuestModelForm(forms.ModelForm):
    class Meta:
        model = GuestsModels
        fields = [
            'name',
            'image',
            'twitter',
            'facebook',
        ]

        labels = {
            'name' : 'Nombre',
            'image' : 'Foto Invitado',
            'twitter' : 'Twitter',
            'facebook' : 'Facebook',
        }

        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),
            'image' : forms.FileInput(),
            'twitter' : forms.TextInput(attrs={'class':'form-control'}),
            'facebook' : forms.TextInput(attrs={'class':'form-control'}),
        }

class ShellersGroupModelForm(forms.ModelForm):
    class Meta:
        model = ShellersGroupModel
        fields = [
            'title',
            'boss',
        ]

        labels = {
            'title' : 'Nombre del grupo',
            'boss' : 'Lider',
        }

        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'boss' : forms.Select(attrs={'class':'selectpicker','data-live-search':'true'}),
        }

class ShellerModelForm(forms.ModelForm):
    class Meta:
        model = ShellerModel
        fields = [
            'user',
        ]

        labels = {
            'user' : 'Vendedor',
        }

        widgets = {
            'user' : forms.Select(attrs={'class':'selectpicker','data-live-search':'true'}),
        }

apps/event_planner/views.py
from django.shortcuts import render

# Create your views here.

apps/events/views.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.utils.timezone import now
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from apps.event_planner.forms import SponsorModelForm, EventPlannerModelForm, GuestModelForm,ShellerModelForm,ShellersGroupModelForm
from apps.events.models import EventModel,ImagesEvent,EventSchedule,TypeEventModel,TypeLocation, GalleryEvent, EventSchedule,RequestAssistance
from apps.events.forms import EventForm, ImagesEventForm, GalleryEventForm, EventScheduleForm

from apps.event_planner.models import EventPlannerModel,GuestsModels,SponsorModel,ShellersGroupModel,ShellerModel
from apps.tickets.forms import TicketModelForm,MethodsPaymentEventOfflineForm
from apps.configplatform.models import ConfigPlatform

from apps.tickets.models import TicketModel,Ticket,MethodsPaymentEvent,PaymentMethod,MethodsPaymentEventOffline

# Create your views here.

def visibility(ticket):
    if (ticket.start_visibility_date < now().date() and ticket.end_visibility_date > now().date()):
        return True
    elif (ticket.start_visibility_date < now().date() and ticket.end_visibility_date == now().date()):
        if (ticket.end_visibility_time > now().time()):
            return True
    elif (ticket.start_visibility_date == now().date() and ticket.end_visibility_date > now().date()):
        if (ticket.start_visibility_time < now().time()):
            return True
    elif (ticket.start_visibility_date == now().date() and ticket.end_visibility_date == now().date()):
        if (ticket.start_visibility_time < now().time() and ticket.end_visibility_time > now().time()):
            return True
    else:
        return False


def EventView(request,view,idevent):
    config = ConfigPlatform.objects.get(id=1)
    if (EventModel.objects.filter(id=idevent).exists()):
        event = EventModel.objects.filter(id=idevent).first()
        if(event.status and TicketModel.objects.filter(event=event).exists() and ImagesEvent.objects.filter(event=event).exists()):
            event_planner = EventPlannerModel.objects.filter(event=event)
            tickets = TicketModel.objects.filter(event=event)
            images = ImagesEvent.objects.filter(event=event)
            guests = GuestsModels.objects.filter(event=event)
            sponsors = SponsorModel.objects.filter(event=event)
            schedules = EventSchedule.objects.all().order_by('start_date','start_time')
            gallery = GalleryEvent.objects.filter(event=event)
            type_events = TypeEventModel.objects.all()

            tickets_view = []
            for ticket in tickets:
                if(ticket.start_sales_date<now().date() and ticket.end_sales_date>now().date()):
                    if(ticket.visibility or  visibility(ticket)):
                        tickets_view.append(ticket)
                elif(ticket.start_sales_date<now().date() and ticket.end_sales_date==now().date()):
                    if(ticket.end_sales_time>now().time()):
                        if (ticket.visibility or visibility(ticket)):
                            tickets_view.append(ticket)
                elif (ticket.start_sales_date == now().date() and ticket.end_sales_date > now().date()):
                    if(ticket.start_sales_time<now().time()):
                        if (ticket.visibility or visibility(ticket)):
                            tickets_view.append(ticket)
                elif (ticket.start_sales_date == now().date() and ticket.end_sales_date == now().date()):
                    if(ticket.start_sales_time<now().time() and ticket.end_sales_time > now().time()):
                        if (ticket.visibility or visibility(ticket)):
                            tickets_view.append(ticket)

            if request.user.username:
                UserRequestAssistance = RequestAssistance.objects.filter(user=request.user).first()

                if UserRequestAssistance and UserRequestAssistance.status or event.user == request.user:
                    ra = True
                else:
                    ra = False

                if event.user == request.user:
                    admin = True
                else:
                    admin = False
            else:
                ra = False
                admin = False

            context = {
             'event' : event,
             'planner' : event_planner,
             'tickets' : tickets,
             'tickets_view' : tickets_view,
             'now' : now(),
             'images' : images,
             'guests' : guests,
             'sponsors' : sponsors,
             'schedules' : schedules,
             'gallery' : gallery,
             'config' : config,
             'request_assistance': ra,
             'admin' : admin,
             'type_events' : type_events,
            }

            if(view == 'home'):
                return render(request, 'event/event_view_home.html', context)
        else:
            return HttpResponse('404')
    else:
        return HttpResponse('404')


def ReqAssistance(request):
    if request.method == 'POST':
        event = EventModel.objects.get(id=request.POST.get("event_id"))
        user = request.user
        request_assistance = RequestAssistance.objects.filter(user=user,event=event).first()
        if request_assistance:
            return JsonResponse({
                'status' : True
            })
        else:
            req = RequestAssistance(user=user,event=event)
            req.save()

            return JsonResponse({
                'status' : True
            })

def Home(request):
    data = []
    events = EventModel.objects.all().order_by('start_date')
    type_events = TypeEventModel.objects.all()
    config = ConfigPlatform.objects.get(id=1)
    for event in events:
        if event.status and event.location_type.id == 2:
            if(TicketModel.objects.filter(event=event).exists()):
                if(ImagesEvent.objects.filter(event=event).exists()):
                    ticket = TicketModel.objects.filter(event=event).order_by('price').first()
                    image = ImagesEvent.objects.filter(event=event).first()

                    data.append({
                        'event': event,
                        'ticket': ticket,
                        'image': image,
                    })

    return render(request,'home/index.html', context={'data': data,'type_events':type_events, 'config':config})

def getEvents(request):
    if request.method == 'POST':
        type_id = int(request.POST.get('type_id'))
        events_response = []
        if(type_id != 0):
            events = EventModel.objects.filter(type_event__id=type_id)
        else:
            events = EventModel.objects.all()

        for event in events:
            if event.status:
                events_response.append({
                    'title':event.title
                })

        return JsonResponse({'events':events_response})

def CreateEvent(request):
    if request.method == 'GET':
        type_events = TypeEventModel.objects.all()
        type_location = TypeLocation.objects.all()
        config = ConfigPlatform.objects.get(id=1)

        return render(request,'event/event_new.html',context={'type_events':type_events,'type_location':type_location,'config':config})
    elif request.method == 'POST':

        if request.POST.get('idevent'):
            event = EventModel.objects.filter(id=request.POST.get('idevent')).first()
            event.title = request.POST.get('title')
            event.url_event = request.POST.get('url_event')
            event.description = request.POST.get('description')
            event.type_event = TypeEventModel.objects.get(id=request.POST.get('id_type'))
            event.location_name = request.POST.get('locationName')
            event.location_address = request.POST.get('locationAddress')
            event.location_state = request.POST.get('locationState')
            event.location_country = request.POST.get('locationCountry')
            event.save()

            return JsonResponse({
                'status' : "change",
            })
        else:
            form = EventForm(request.POST)

            if form.is_valid():
                event = form.save(commit=False)
                event.user = User.objects.filter(id=request.user.id).first()
                newevent = form.save()

                return JsonResponse({
                    'status' : "OK",
                    'id_event' : newevent.id,
                })
            else:
                return JsonResponse({
                    'status' : "Error",
                    'errors' : form.errors,
                })

            #return redirect('events:dashboard',newevent.id)

def DashboardEvent(request,idevent):
    if request.method == 'GET':
        type_events = TypeEventModel.objects.all()
        event = EventModel.objects.filter(id=idevent).first()
        tickets = TicketModel.objects.filter(event=event).order_by('price')
        images= ImagesEvent.objects.filter(event=event)
        shellers = ShellersGroupModel.objects.filter(event=event)
        guests = GuestsModels.objects.filter(event=event)
        planners = EventPlannerModel.objects.filter(event=event)
        gallery = GalleryEvent.objects.filter(event=event)
        sponsors = SponsorModel.objects.filter(event=event)
        schedules = EventSchedule.objects.filter(event=event)
        config = ConfigPlatform.objects.get(id=1)
        request_assistance = RequestAssistance.objects.filter(event=event,status=False)

        if(request.user == event.user):
            context = {
                'event': event,
                'tickets':tickets,
                'images':images,
                'config':config,
                'type_events':type_events,

templates/event/event_dashboard.html
{% extends "event/base/index.html" %}


{% block container %}
<div class="margin_30 container-fluid">
        {% if tickets and images%}
            {% if event.status %}
                <a href="{% url 'events:publish' event.id %}" class="btn_full green">Cerrar Evento</a>
            {% else %}
                <a href="{% url 'events:publish' event.id %}" class="btn_full green">Publicar Evento</a>
            {% endif %}
        {% endif %}

        {% include "event/base/sidebar_nav_event.html" %}

        <div class="col-md-10">
          <div class="col-md-8">
            <div class="row">
              <div class="col-md-4" style="position:relative;padding-top:1.8em;">
                <h4 style="font-weight:bold;"><span class="icon-ticket" style="color:{{config.color_one}};"></span>Tickets</h4>
                <canvas id="statsTickets" width="400" height="400"></canvas>
                <p style="position:absolute;font-size:1em;top:35%;left:15%;">Dinero recaudado</p>
                <p style="position:absolute;font-size:2.4em;top:46%;left:15%;" id="raised_money"></p>
                <p style="position:absolute;font-size:2.4em;top:46%;left:15%;" id="tickets_sold"></p>
              </div>
              <div class="col-md-4" style="padding-top:1.8em;">
                <h4 style="font-weight:bold;"><span class="icon-newspaper" style="color:{{config.color_one}};"></span>Aceptar Asistencia</h4>
                <div style="height: 200px; overflow:auto;">
                  <table class="table">
                    {% if assistance %}
                    <tbody id="assistances">
                        {% for assis in assistance %}
                          <tr id="assistance-{{assis.id}}">
                            <td>{{assis.user.username}}</td>
                            <td><button type="button" onclick="toAccept({{assis.id}})"  class="btn btn-green" name="button"><i class="icon-check-1"></i></button></td>
                          </tr>
                        {% endfor %}
                    </tbody>
                    {% else %}
                      <p style="text-align:center; font-weight:bold; font-size:1.2em;color: rgba(0,0,0,.5); margin-botton:-200px;">No hay nuevas solicitudes</p>
                      <p class="text-center" style="color: rgba(0,0,0,.3);">Si tu evento es privado, aqui podras visualizar las solicitudes de los usuarios que deseen asistir y comprar tickets.</p>
                    {% endif %}
                  </table>
                </div>
              </div>
              <div class="col-md-4" style="padding-top:1.8em;">
                <h4 style="font-weight:bold;"><span class="icon-money" style="color:{{config.color_one}};"></span> Metodos De Pago</h4>
                {% if methodspaymentevent %}

                {% else %}
                  <p style="text-align:center; font-weight:bold; font-size:1.2em;color: rgba(0,0,0,.5); margin-botton:-200px;">No hay metodos de pago</p>
                  <p class="text-center" style="color: rgba(0,0,0,.3);">Puedes configurar tu cuenta en alguna de las pasarelas de pago que te ofrecemos.</p>
                  <p class="text-center"><a href="{% url 'events:event_configurations' event.id %}" class="btn_1 blue"><i class="icon-tools"></i>Configurar</a></p>
                {% endif %}
              </div>
            </div>
            <div class="row">
              <h4 style="font-weight:bold;"><span class="icon-clock" style="color:{{config.color_one}};"></span>Ultimas Transacciones</h4>
              <div class="col-md-11">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Comprador</th>
                      <th>Ticket</th>
                      <th>Precio</th>
                      <th>Fecha</th>
                      <th>Metodo</th>
                    </tr>
                  </thead>
                  <tbody id="transactions">
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-md-4">
                 <div class="row">
                    <div class="hotel_container">
                        <div class="img_container">
                            {% with images|first as image %}
                            <img src="{{ image.image.url }}" style="width: 100%; height: 250px;" class="img-responsive" alt="Image">
                            {% endwith %}
                            <div class="short_info hotel">
                                <i class="{{event.type_event.icon}}"></i>{{ event.type_event.tile }}
                                 {% with tickets|first as ticket %}
                                 <span class="price"><sup>Desde ${{ ticket.price }}0</sup></span>
                                 {% endwith %}
                            </div>
                        </div>
                        <div class="hotel_title">
                            <h3><strong>{{ event.title }}</strong></h3>
                            <div class="rating">
                                <i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star-empty"></i>
                            </div><!-- end rating -->
                        </div>
                    </div><!-- End box tour -->
               </div><!-- End row -->

              <div class="row">
                  {% if tickets %}
                      <div class="alert alert-success">
                        <strong class="icon icon-check-1"></strong> Tienes creado un ticket
                      </div>
                  {% else %}
                      <div class="alert alert-danger">
                        <strong>Falta!</strong> Debes Crear almenos un ticket
                      </div>
                  {% endif %}

                  {% if images %}
                      <div class="alert alert-success">
                        <strong class="icon icon-check-1"></strong> Tienes la imagen de tu evento
                      </div>
                  {% else %}
                      <div class="alert alert-danger">
                        <strong>Falta!</strong> Debes añadir una imagen para tu evento
                      </div>
                  {% endif %}
              </div>
          </div>
        </div>
</div><!-- end container -->
{% endblock %}

{% block js_specific %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
  <script>

  $(function() {
      $.ajax({
          url : "{% url 'events:statsTickets' %}", // the endpoint
          type : "POST", // http method
          data : {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            id_event : '{{event.id}}',
          }, // data sent with the post request

          // handle a successful response
          success : function(json) {
              console.log(json); // log the returned json to the console

              $('#raised_money').text("$"+json.total);

              var ctx = document.getElementById("statsTickets");
              var myChart = new Chart(ctx, {
                  type: 'bar',
                  data: {
                      labels: json.titles,
                      datasets: [{
                          label: '$',
                          data: json.money,
                      }]
                  },
                  options: {
                      scales: {
                          yAxes: [{
                              ticks: {
                                  display: false,
                              }
                          }],
                          xAxes: [{
                              ticks: {
                                  display: false
                              }
                          }]
                      },
                      showXAxisLabel:false,
                      legend: {
                          display: false
                      },
                      responsive: true,
                  }
              });
          },

          // handle a non-successful response
          error : function(xhr,errmsg,err) {
              console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
          }
      });
  })

  $(function() {
      $.ajax({
          url : "{% url 'events:ticketsSold' %}",
          type : "POST",
          data : {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            id_event : '{{event.id}}',
          },

          success : function(json) {
              count_transactions = 0;
              for (var i = json.tickets_sold_list.length-1; i >= 0; i--) {
                if (count_transactions<5) {
                  date = new Date(json.tickets_sold_list[i].date);
                  date_new = date.getDay() + "/" + (date.getMonth()+1) + "/" + date.getFullYear() + " - " + date.getHours()+":"+ date.getMinutes();
                  row = "<tr>" +"<td>"+json.tickets_sold_list[i].user+"</td>" +"<td>"+json.tickets_sold_list[i].ticket+"</td>" +"<td>"+json.tickets_sold_list[i].price+"</td>"+"<td>"+date_new+"</td>"+"<td>"+json.tickets_sold_list[i].method+"</td>"+"</tr>";
                  $('#transactions').append(row)
                }
                count_transactions+=1;
              }
          },

          error : function(xhr,errmsg,err) {
              console.log(xhr.status + ": " + xhr.responseText);
          }
      });
  })

  function toAccept(id) {
    $.ajax({
        url : "{% url 'events:toaccept' %}",
        type : "POST",
        data : {
          csrfmiddlewaretoken: '{{ csrf_token }}',
          idRequestAssistance : id,
        },

        success : function(json) {
            console.log(json);
            $('#assistance-'+json.idRequestAssistance).remove();
        },

        error : function(xhr,errmsg,err) {
            console.log(xhr.status + ": " + xhr.responseText);
        }
    });
  }
  </script>
{% endblock  %}

templates/event/event_gallery.html
{% extends "event/base/index.html" %}

{% block title_section %}
  Galeria
{% endblock %}

{% block li_section %}
  <li><a href="{% url 'events:event_gallery' event.id %}">Galeria</a></li>
{% endblock %}

{% block container %}
  <div class="margin_30 container-fluid">
    {% include "event/base/sidebar_nav_event.html" %}
        <div class="col-md-6">
            {% if model.count > 0 %}
                {% for image in model %}
                    <div class="col-md-4" style="position:relative;" id="image-{{image.id}}">
                        <img src="{{ image.image.url }}" alt="{{image.image.id}}" width="100%" height="150px">
                        <button style="background-color: #FE2E2E; border:2px solid white; border-radius:50%; padding:5px 7px; color:white; position:absolute; top:-5%; left:85%; " type="button" name="button" onclick="Delete({{image.id}})"><span class="icon-trash-1"></span></button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="col-md-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn_full green" value="Guardar">
            </form>
        </div>
  </div><!-- end container -->
{% endblock %}

{% block js_specific %}
  <script>
      function Delete(id) {
        conf = confirm("Desea eliminar este elemento?");
        if (conf==true) {
          $.ajax({
            url : "{% url 'events:event_delete' event.id %}" , // the endpoint
            type : "POST", // http method
            data : {
              csrfmiddlewaretoken: '{{ csrf_token }}',
              model : 'gallery',
              id_model : id,
            }, // data sent with the post request
            // handle a successful response
            success : function(json) {
                //console.log(json); // log the returned json to the console
                $("#image-"+json.id).remove();
            },

            // handle a non-successful response
            error : function(xhr,errmsg,err) {
                console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
            }
          });
        }
      }
  </script>
{% endblock %}