apps/events/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.events.views import EventView,CreateEvent,DashboardEvent,EventImages,EventTicket,PublishEvent,EventPlanner,EventSponsor,EventGuest,Delete,EventGallery,EventSchedules,getEvents,GetStatsTickets,TicketsSold,ReqAssistance,toAccept,EventShellers,addShellerInTheGroup,destroyEvent,EventConfigurations,changeOptionEvent,EventMethodsPaymentEventOffline,configPlatformPayment

urlpatterns = [
    url(r'^new$', login_required(CreateEvent), name='new'),
    url(r'^view/(?P<view>\w+)/(?P<idevent>\d+)/$', EventView, name='event_view_home'), #Basada en funciones
    url(r'^dashboard/(?P<idevent>\d+)/$', login_required(DashboardEvent), name='dashboard'), #Basada en funciones
    url(r'^dashboard/images/(?P<idevent>\d+)/$', login_required(EventImages), name='event_images'),  # Basada en funciones
    url(r'^dashboard/gallery/(?P<idevent>\d+)/$', login_required(EventGallery), name='event_gallery'),  # Basada en funciones
    url(r'^dashboard/tickets/(?P<idevent>\d+)/$', login_required(EventTicket), name='event_tickets'),# Basada en funciones
    url(r'^dashboard/publish/(?P<idevent>\d+)/$', login_required(PublishEvent), name='publish'),# Basada en funciones
    url(r'^dashboard/planners/(?P<idevent>\d+)/$', login_required(EventPlanner), name='event_planners'),# Basada en funciones
    url(r'^dashboard/sponsors/(?P<idevent>\d+)/$', login_required(EventSponsor), name='event_sponsors'),# Basada en funciones
    url(r'^dashboard/guests/(?P<idevent>\d+)/$', login_required(EventGuest), name='event_guests'),# Basada en funciones
    url(r'^dashboard/schedules/(?P<idevent>\d+)/$', login_required(EventSchedules), name='event_schedules'),# Basada en funciones
    url(r'^dashboard/shellers/(?P<idevent>\d+)/$', login_required(EventShellers), name='event_shellers'),# Basada en funciones
    url(r'^dashboard/configurations/(?P<idevent>\d+)/$', login_required(EventConfigurations), name='event_configurations'),# Basada en funciones
    url(r'^dashboard/paymentoffline/(?P<idevent>\d+)/$', login_required(EventMethodsPaymentEventOffline), name='paymentoffline'),# Basada en funciones
    url(r'^dashboard/delete/(?P<idevent>\d+)/$', login_required(Delete), name='event_delete'),
    url(r'^search/$', login_required(getEvents), name='getEvents'),
    url(r'^stats/tickets/$', login_required(GetStatsTickets), name='statsTickets'),
    url(r'^sold/tickets/$', login_required(TicketsSold), name='ticketsSold'),
    url(r'^requestassistance/$', login_required(ReqAssistance), name='reqassistance'),
    url(r'^toaccept/$', login_required(toAccept), name='toaccept'),
    url(r'^addsheller/$', login_required(addShellerInTheGroup), name='addsheller'),
    url(r'^destroy/$', login_required(destroyEvent), name='destroy'),
    url(r'^change_option/$', login_required(changeOptionEvent), name='changeOption'),
    url(r'^platformpayment/$', login_required(configPlatformPayment), name='platformpayment'),
]

iticket/urls.py
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm,password_reset_complete

from apps.events.views import Home
from apps.users.views import UserRegister

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include ('apps.events.urls', namespace="events")),
    url(r'^tickets/', include ('apps.tickets.urls', namespace="tickets")),
    url(r'^profile/', include('apps.users.urls', namespace="profile")),
    url(r'^register/', UserRegister, name="register"),
    url(r'^$', Home, name='home'),
    url(r'^accounts/login/', login, {'template_name': 'index.html'}, name='login'),
    url('', include('social_django.urls', namespace='social')),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, {'template_name': 'registration/password_reset_form.html', 'email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'} , name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, {'template_name':'registration/password_reset_confirm.html'} ,name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete,{'template_name':'registration/password_reset_complete.html'} ,name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/events/views.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.utils.timezone import now
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from apps.event_planner.forms import SponsorModelForm, EventPlannerModelForm, GuestModelForm,ShellerModelForm,ShellersGroupModelForm
from apps.events.models import EventModel,ImagesEvent,EventSchedule,TypeEventModel,TypeLocation, GalleryEvent, EventSchedule,RequestAssistance
from apps.events.forms import EventForm, ImagesEventForm, GalleryEventForm, EventScheduleForm

from apps.event_planner.models import EventPlannerModel,GuestsModels,SponsorModel,ShellersGroupModel,ShellerModel
from apps.tickets.forms import TicketModelForm,MethodsPaymentEventOfflineForm
from apps.configplatform.models import ConfigPlatform

from apps.tickets.models import TicketModel,Ticket,MethodsPaymentEvent,PaymentMethod,MethodsPaymentEventOffline

# Create your views here.

def visibility(ticket):
    if (ticket.start_visibility_date < now().date() and ticket.end_visibility_date > now().date()):
        return True
    elif (ticket.start_visibility_date < now().date() and ticket.end_visibility_date == now().date()):
        if (ticket.end_visibility_time > now().time()):
            return True
    elif (ticket.start_visibility_date == now().date() and ticket.end_visibility_date > now().date()):
        if (ticket.start_visibility_time < now().time()):
            return True
    elif (ticket.start_visibility_date == now().date() and ticket.end_visibility_date == now().date()):
        if (ticket.start_visibility_time < now().time() and ticket.end_visibility_time > now().time()):
            return True
    else:
        return False


def EventView(request,view,idevent):
    config = ConfigPlatform.objects.get(id=1)
    if (EventModel.objects.filter(id=idevent).exists()):
        event = EventModel.objects.filter(id=idevent).first()
        if(event.status and TicketModel.objects.filter(event=event).exists() and ImagesEvent.objects.filter(event=event).exists()):
            event_planner = EventPlannerModel.objects.filter(event=event)
            tickets = TicketModel.objects.filter(event=event)
            images = ImagesEvent.objects.filter(event=event)
            guests = GuestsModels.objects.filter(event=event)
            sponsors = SponsorModel.objects.filter(event=event)
            schedules = EventSchedule.objects.all().order_by('start_date','start_time')
            gallery = GalleryEvent.objects.filter(event=event)
            type_events = TypeEventModel.objects.all()

            tickets_view = []
            for ticket in tickets:
                if(ticket.start_sales_date<now().date() and ticket.end_sales_date>now().date()):
                    if(ticket.visibility or  visibility(ticket)):
                        tickets_view.append(ticket)
                elif(ticket.start_sales_date<now().date() and ticket.end_sales_date==now().date()):
                    if(ticket.end_sales_time>now().time()):
                        if (ticket.visibility or visibility(ticket)):
                            tickets_view.append(ticket)
                elif (ticket.start_sales_date == now().date() and ticket.end_sales_date > now().date()):
                    if(ticket.start_sales_time<now().time()):
                        if (ticket.visibility or visibility(ticket)):
                            tickets_view.append(ticket)
                elif (ticket.start_sales_date == now().date() and ticket.end_sales_date == now().date()):
                    if(ticket.start_sales_time<now().time() and ticket.end_sales_time > now().time()):
                        if (ticket.visibility or visibility(ticket)):
                            tickets_view.append(ticket)

            if request.user.username:
                UserRequestAssistance = RequestAssistance.objects.filter(user=request.user).first()

                if UserRequestAssistance and UserRequestAssistance.status or event.user == request.user:
                    ra = True
                else:
                    ra = False

                if event.user == request.user:
                    admin = True
                else:
                    admin = False
            else:
                ra = False
                admin = False

            context = {
             'event' : event,
             'planner' : event_planner,
             'tickets' : tickets,
             'tickets_view' : tickets_view,
             'now' : now(),
             'images' : images,
             'guests' : guests,
             'sponsors' : sponsors,
             'schedules' : schedules,
             'gallery' : gallery,
             'config' : config,
             'request_assistance': ra,
             'admin' : admin,
             'type_events' : type_events,
            }

            if(view == 'home'):
                return render(request, 'event/event_view_home.html', context)
        else:
            return HttpResponse('404')
    else:
        return HttpResponse('404')


def ReqAssistance(request):
    if request.method == 'POST':
        event = EventModel.objects.get(id=request.POST.get("event_id"))
        user = request.user
        request_assistance = RequestAssistance.objects.filter(user=user,event=event).first()
        if request_assistance:
            return JsonResponse({
                'status' : True
            })
        else:
            req = RequestAssistance(user=user,event=event)
            req.save()

            return JsonResponse({
                'status' : True
            })

def Home(request):
    data = []
    events = EventModel.objects.all().order_by('start_date')
    type_events = TypeEventModel.objects.all()
    config = ConfigPlatform.objects.get(id=1)
    for event in events:
        if event.status and event.location_type.id == 2:
            if(TicketModel.objects.filter(event=event).exists()):
                if(ImagesEvent.objects.filter(event=event).exists()):
                    ticket = TicketModel.objects.filter(event=event).order_by('price').first()
                    image = ImagesEvent.objects.filter(event=event).first()

                    data.append({
                        'event': event,
                        'ticket': ticket,
                        'image': image,
                    })

    return render(request,'home/index.html', context={'data': data,'type_events':type_events, 'config':config})

def getEvents(request):
    if request.method == 'POST':
        type_id = int(request.POST.get('type_id'))
        events_response = []
        if(type_id != 0):
            events = EventModel.objects.filter(type_event__id=type_id)
        else:
            events = EventModel.objects.all()

        for event in events:
            if event.status:
                events_response.append({
                    'title':event.title
                })

        return JsonResponse({'events':events_response})

def CreateEvent(request):
    if request.method == 'GET':
        type_events = TypeEventModel.objects.all()
        type_location = TypeLocation.objects.all()
        config = ConfigPlatform.objects.get(id=1)

        return render(request,'event/event_new.html',context={'type_events':type_events,'type_location':type_location,'config':config})
    elif request.method == 'POST':

        if request.POST.get('idevent'):
            event = EventModel.objects.filter(id=request.POST.get('idevent')).first()
            event.title = request.POST.get('title')
            event.url_event = request.POST.get('url_event')
            event.description = request.POST.get('description')
            event.type_event = TypeEventModel.objects.get(id=request.POST.get('id_type'))
            event.location_name = request.POST.get('locationName')
            event.location_address = request.POST.get('locationAddress')
            event.location_state = request.POST.get('locationState')
            event.location_country = request.POST.get('locationCountry')
            event.save()

            return JsonResponse({
                'status' : "change",
            })
        else:
            form = EventForm(request.POST)

            if form.is_valid():
                event = form.save(commit=False)
                event.user = User.objects.filter(id=request.user.id).first()
                newevent = form.save()

                return JsonResponse({
                    'status' : "OK",
                    'id_event' : newevent.id,
                })
            else:
                return JsonResponse({
                    'status' : "Error",
                    'errors' : form.errors,
                })

            #return redirect('events:dashboard',newevent.id)

def DashboardEvent(request,idevent):
    if request.method == 'GET':
        type_events = TypeEventModel.objects.all()
        event = EventModel.objects.filter(id=idevent).first()
        tickets = TicketModel.objects.filter(event=event).order_by('price')
        images= ImagesEvent.objects.filter(event=event)
        shellers = ShellersGroupModel.objects.filter(event=event)
        guests = GuestsModels.objects.filter(event=event)
        planners = EventPlannerModel.objects.filter(event=event)
        gallery = GalleryEvent.objects.filter(event=event)
        sponsors = SponsorModel.objects.filter(event=event)
        schedules = EventSchedule.objects.filter(event=event)
        config = ConfigPlatform.objects.get(id=1)
        request_assistance = RequestAssistance.objects.filter(event=event,status=False)

        if(request.user == event.user):
            context = {
                'event': event,
                'tickets':tickets,
                'images':images,
                'config':config,
                'type_events':type_events,

templates/event/base/footer_view_event.html
<footer id="qcFooter" class="clearfix">
	<div class="qcContainer">

		<!-- ## FOOTER NAV ## -->
		<div class="col-5 col">
			<nav id="qcFooterNav">
				<ul class="clearfix">
					<li><a href="{%url 'home' %}">Inicio</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</nav>
		</div>

		<!-- ## FOOTER LOGO ## -->
		<div id="qcFooterLogo" class="col-2 col">
			<a href="{% url 'home' %}">
				<img src="{{config.logo.url}}" alt="{{config.title}}" width="100" height="60"/>
			</a>
		</div>

		<!-- ## FOOTER COPYRIGHTS ## -->
		<div id="qcFooterPara" class="col-5 col">
			<p><span>&copy;{{config.title}}</span></p>
		</div>

	</div>
</footer>

templates/event/base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Citytours - Premium site template for city tours agencies, transfers and tickets.">
    <meta name="author" content="Ansonika">
    <title>{{config.title}}|{{event.title}}</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="{% static 'img/home/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="{% static 'img/home/apple-touch-icon-72x72-precomposed.png' %}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="{% static 'img/home/apple-touch-icon-114x114-precomposed.png' %}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="{% static 'img/home/apple-touch-icon-144x144-precomposed.png' %}">

    <!-- CSS -->
    <link href="{% static 'css/home/base.css' %}" rel="stylesheet">


    <!-- SPECIFIC CSS -->
    <link href="{% static 'css/home/admin.css' %}" rel="stylesheet">
    <link href="{% static 'css/event/event_admin.css' %}" rel="stylesheet">
    <link href="{% static 'css/home/jquery.switch.css' %}" rel="stylesheet">

    {% include "base/style.html" %}

    {% block css_specific %}

    {% endblock %}

    <!-- Google web fonts -->
   <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
   <link href='http://fonts.googleapis.com/css?family=Gochi+Hand' rel='stylesheet' type='text/css'>
   <link href='http://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'>

</head>
<body>

    <div id="preloader">
        <div class="sk-spinner sk-spinner-wave">
            <div class="sk-rect1"></div>
            <div class="sk-rect2"></div>
            <div class="sk-rect3"></div>
            <div class="sk-rect4"></div>
            <div class="sk-rect5"></div>
        </div>
    </div>
    <!-- End Preload -->

    <div class="layer"></div>
    <!-- Mobile menu overlay mask -->

     <!-- Header================================================== -->
    <header>
        <div id="top_line">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-6"><strong></strong></div>

                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <ul id="top_links">
                            <li>
                                <div class="dropdown dropdown-access">
                                    <a href="{% url 'logout' %}?next={% url 'home' %}" id="access_link">Cerrar Sesión</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div><!-- End row -->
            </div><!-- End container-->
        </div><!-- End top line-->

        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-3 col-xs-3">
                    <div id="logo">
                        <a href="{% url 'home' %}"><img src="{{config.logo.url}}" width="100" height="60" alt="City tours" data-retina="true" class="logo_normal"></a>
                        <a href="{% url 'home' %}"><img src="{{config.logo.url}}" width="100" height="60" alt="City tours" data-retina="true" class="logo_sticky"></a>
                    </div>
                </div>
                <nav class="col-md-9 col-sm-9 col-xs-9">
                    <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
                    <div class="main-menu">
                        <div id="header_menu">
                            <img src="{{config.logo.url}}" width="100" height="60" alt="City tours" data-retina="true">
                        </div>
                        <a href="#" class="open_close" id="close_in"><i class="icon_set_1_icon-77"></i></a>
                        {% include "base/nav.html" %}
                    </div><!-- End main-menu -->
                </nav>
            </div>
        </div><!-- container -->
    </header><!-- End Header -->


<section class="parallax-window" data-parallax="scroll" data-image-src="{{config.banner_one.url}}" data-natural-width="1400" data-natural-height="470">
    <div class="parallax-content-1">
        <div class="animated fadeInDown">
        	<h1>{{ event.title }} | {% block title_section %}Dashboard{% endblock %}</h1>
        	<p>{{ event.description }}</p>
        </div>
    </div>
</section><!-- End section -->

<div id="position">
    	<div class="container">
                	<ul>
                    <li><a href="{% url 'home' %}">Inicio</a></li>
                    <li><a href="{% url 'profile:home' user.username %}">Perfil</a></li>
                    <li><a href="{% url 'events:dashboard' event.id %}">{{ event.title }}</a></li>
                    {% block li_section %}{% endblock %}
                    </ul>
        </div>
</div><!-- End Position -->

{% block container %}
{% endblock %}

{% include "base/footer.html" %}

<div id="toTop"></div><!-- Back to top button -->


<!-- Common scripts -->
<script src="{% static 'js/home/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/home/common_scripts_min.js' %}"></script>
<script src="{% static 'js/home/functions.js' %}"></script>
<script src="{% static 'js/datepicker.js' %}"></script>

{% block js_specific %}

{% endblock %}


<script>
    $('.form_date').datetimepicker({
      weekStart: 1,
      todayBtn:  1,
      autoclose: 1,
      todayHighlight: 1,
      startView: 2,
      minView: 2,
      forceParse: 0
    });

    $('.form_time').datetimepicker({
        weekStart: 1,
        todayBtn:  1,
    		autoclose: 1,
    		todayHighlight: 1,
    		startView: 1,
    		minView: 0,
    		maxView: 1,
    		forceParse: 0
    });
</script>

  </body>
</html>

templates/event/base/sidebar_nav_event.html
<div class="col-md-2">

  <ul class="list-group">
    <li class="list-group-item">
      <a href="{% url 'events:dashboard' event.id %}"><span class="icon-heart"></span> {{event.title}}</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'events:event_configurations' event.id %}"><span class="icon-tools"></span> Configuraciones</a>
    </li>
  </ul>

  <ul class="list-group">
    <li class="list-group-item">
      <a href="{% url 'events:event_images' event.id %}"><span class="icon-picture-5"></span> Imagenes</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'events:event_gallery' event.id %}"><span class=" icon-camera-7"></span> Galeria</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'events:event_planners' event.id %}"><span class="icon-user-pair"></span> Organizadores</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'events:event_shellers' event.id %}"><span class="icon-money"></span> Vendedores</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'events:event_tickets' event.id %}"><span class="icon-ticket-1"></span> Tickets</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'events:event_sponsors' event.id %}"><span class="icon-megaphone"></span> Patrocinadores</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'events:event_guests' event.id %}"><span class="icon-users-2"></span> Invitados</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'events:event_schedules' event.id %}"><span class="icon-calendar"></span> Cronograma</a>
    </li>
  </ul>
</div>